### ISSUE TITLE
tests for `csrf.middleware`

### ISSUE THREAD

**Issue by stephenmathieson** [koajs/csrf#19]
i can't seem to get it working, but `app.use(require('koa-csrf')())` works fine.  since `csrf.middleware` is the suggested way of using this thing, i'm surprised there are no tests for it

**Comment by jonathanong** [comment]
@fengmk2 @dead-horse i think you guys added the middleware feature

**Comment by jonathanong** [comment]
@stephenmathieson invited you to @koajs/sessions if you're interested in helping out

**Comment by dead-horse** [comment]
@stephenmathieson 

there have some [test cases](https://github.com/koajs/csrf/blob/master/test/middleware.test.js) for middleware usage, and I fixed the [example](https://github.com/koajs/csrf#middleware), you can check it out.

**Comment by stephenmathieson** [comment]
thanks @jonathanong.  not sure if i want the responsibility, but i'll think about it :)

@dead-horse the test cases don't use `csrf.middleware`.  they use [`csrf()`](https://github.com/koajs/csrf/blob/2.4.0/test/middleware.test.js#L144) instead

**Comment by dead-horse** [comment]
@stephenmathieson it's a simplified way to using csrf as a middleware

**Comment by stephenmathieson** [comment]
Default signature has changed. Closing for now.
