### ISSUE TITLE
Upgrading to Koa2.0

### ISSUE THREAD

**Issue by rgranger** [koajs/csrf#25]
Hi, I was just wondering if there was any plan to upgrade to Koa2.0
Thanks.

**Comment by niftylettuce** [comment]
bump

**Comment by jonathanong** [comment]
adding @niftylettuce as a contributor. no excuses now

**Comment by niftylettuce** [comment]
Haha okay 💃 💃

**Comment by niftylettuce** [comment]
I'll submit a PR soon 😉

**Comment by niftylettuce** [comment]
@jonathanong @rgranger done, published v3.0.0 to NPM and GitHub, needs some more work, see <https://github.com/koajs/csrf#open-source-contributor-requests>

**Comment by niftylettuce** [comment]
Had a bug with 3.0.0, I re-released and unpublished 3.0.0, the latest version is 3.0.1 with koa@next support 😄

**Comment by niftylettuce** [comment]
Versions 3.0.0, 3.0.1, and 3.0.2 had a bug with constantly setting a new session secret (this is only supposed to be set once).  I have fixed this per and release v3.0.3 (and also added a new deprecation notice to versions 3.0.3)
