### ISSUE TITLE
Why assertCsrf method given a body value?

### ISSUE THREAD

**Issue by kenchan0130** [koajs/csrf#26]
Currently, `assertCsrf` method has the body argument.

But I thought it look like that `assertCsrf` method presuppose `request.body`.

I seem that some developer have to understand [those implements]( https://github.com/koajs/csrf/blob/master/index.js#L71-L74).

So, the `body` argument of `assertCsrf` method should have like default value which is `this.request.body`.

What do you think?

**Comment by niftylettuce** [comment]
Can you take a look at the new code for Koa@next here and let me know if this is still an issue or how we can fix it? <https://github.com/koajs/csrf>
