### ISSUE TITLE
why deprecate csrf@2

### ISSUE THREAD

**Issue by dead-horse** [koajs/csrf#28]
> koa-csrf@2.5.0 deprecate: If you are using Koa v3.x, please make sure you are on at least 3.0.3 due to CSRF session reset issue (prevents XHR from working properly for example)

is this a mistake?

**Comment by shaoshuai0102** [comment]
same question here

**Comment by niftylettuce** [comment]
Ah I forgot to make it > 3 and < 3.0.3.  I can fix.

**Comment by niftylettuce** [comment]
I went ahead and removed the deprecation notice.  I'm not sure how to write this... `npm deprecate koa-csrf@"<3.0.3&>=3.0.0`... do either of you @dead-horse @shaoshuai0102?

**Comment by niftylettuce** [comment]
cc @jonathanong how do you write a deprecation notice between two versions?  I'm not sure how.

**Comment by ngot** [comment]
How about this now？

**Comment by atian25** [comment]
@niftylettuce any progress?

**Comment by niftylettuce** [comment]
no progress, I don't know how to do it, other than if we add a Readme notice

**Comment by luckydrq** [comment]
Sorry, but what does the `CSRF session reset issue` refer to?
