### ISSUE TITLE
Importing koa-csrf in node 6

### ISSUE THREAD

**Issue by suhas-babyoye** [koajs/csrf#31]
To be able to import `CSRF` in node 6.x we have to write like this:

``` js
const CSRF = require('koa-csrf').default;
```

Is this the right way? Also, the README.md example doesn't import CSRF at all(although it is using es6 modules).

**Comment by kingjerod** [comment]
The example provided is really bad. I'm not sure why they didn't implement it like so:
 `app.use(require('koa-csrf'))`
or 
`
var csrf = require('koa-csrf');
app.use(new csrf({}));
`

This is what almost all other koa middlewares do. At least update the example to work.  =/
