### ISSUE TITLE
Can i disable CSRF check for some routes?

### ISSUE THREAD

**Issue by justkost** [koajs/csrf#46]

**Comment by stephenmathieson** [comment]
Yes. You can avoid CSRF checks by not mounting the middleware.

**Comment by arunrreddy** [comment]
How do you conditionally mount or not mount the middleware?

**Comment by stephenmathieson** [comment]
You can do something like:

```js
var app = new Koa()
var middleware = new CSRF({ ...  })
app.post('/with-csrf', middleware, (ctx, next) => { ... })
app.post('/without-csrf', (ctx, next) => { ... })
app.post('/another/with-csrf', middleware, (ctx, next) => { ... })
```

**Comment by arunrreddy** [comment]
async function conditionalCsrf(ctx, next) {
    debug('Entered conditional csrf middleware');
    const request = ctx.request;
    debug(request.path, !_.includes(request.path, '/webhook/'));
    if(!_.includes(request.path, '/webhook/')) {
       return new CSRF(); // eslint-disable-line
    }
    await next(); // eslint-disable-line
};

app.use(conditionalCsrf);
 I am trying to use it like this since I have a number of middlewares to be executed. I am unable to get it to work this way.

**Comment by stephenmathieson** [comment]
There's a similar example in the README:

```js
app.use((ctx, next) => {
  if (![ 'GET', 'POST' ].includes(ctx.method))
    return next();
  if (ctx.method === 'GET') {
    ctx.body = ctx.csrf;
    return;
  }
  ctx.body = 'OK';
});
```

So rather than checking the request method, you could check the request path.

**Comment by arunrreddy** [comment]
The above example is just setting the generated csrf in the koa context. In the docs, above your written middleware there is app.use(new CSRF()) defined. I trying to conditionally mount that middleware.
